### ISSUE TITLE
References to MongoDB under learn-performance

### ISSUE THREAD

**Issue by hawk4031** [ibm-cloud-docs/databases-for-postgresql#10]
In the learn-performance markdown file, the second paragraph titled `Monitoring your deployment` has references to MongoDB, including the links. Should these be changed to Postgres instead?

**Comment by DailyAlice** [comment]
Yes! you're right. This should be fixed with [commit 5f9f186](https://github.com/ibm-cloud-docs/databases-for-postgresql/commit/5f9f186bdf59e9c5498e97a411f9be63c306f512).

Thank you.
