### ISSUE TITLE
the link for read-only replicas is wrong

### ISSUE THREAD

**Issue by bikasprice** [ibm-cloud-docs/databases-for-postgresql#12]
The following line:
You can extend high-availability to more regions and spread to more replicas by adding read-only replicas.
(last sentence in the first section) has an href for read-only replicas

That link currently is. https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-read-only-replicass
which is an invalid link, we need to remove the trailing 's' and make it

https://cloud.ibm.com/docs/databases-for-postgresql?topic=databases-for-postgresql-read-only-replicas

**Comment by acdntlpoet** [comment]
Fixed all broken links and republished.
