### ISSUE TITLE
Incorrect value for default number of members on "Adding PostgreSQL Members" page

### ISSUE THREAD

**Issue by bryand2** [ibm-cloud-docs/databases-for-postgresql#13]
The last example of the page says "The example request increases the number of members from the default of 3 to 5."   This is incorrect.  The default number of members is 2.  A better example would be to increase from 2-3 (as there are 3 availability zones).

**Comment by acdntlpoet** [comment]
Corrected and republished. Thank you!

**Comment by bryand2** [comment]
thank-you! Looks great!
