### ISSUE TITLE
Duplicate page in the nav?

### ISSUE THREAD

**Issue by sgraden** [ibm-cloud-docs/databases-for-postgresql#4]
There seem to be two places in the left navigation linking to the same page which caused some confusion. P.S. Internal IBMer :D

Page name: Creating Users and Getting Connection Strings
https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-connection-strings

![image](https://user-images.githubusercontent.com/6685872/57813902-62712680-7737-11e9-83ce-e8c1f9683c98.png)

**Comment by DailyAlice** [comment]
This eventually got fixed between here and now, but thank you for pointing it out!
