### ISSUE TITLE
Missing CLI and API commands for promoting a read-only replica

### ISSUE THREAD

**Issue by rpiras** [ibm-cloud-docs/databases-for-postgresql#7]
I could not find the CLI and API commands for promoting a read-only replica.
Is this a glitch?

**Comment by DailyAlice** [comment]
Added the commands in the [latest commit](https://github.com/ibm-cloud-docs/databases-for-postgresql/commit/9448ce18388d26c8cb529aa8891c6d27ebaba0cc).

Thanks for letting us know.
