### ISSUE TITLE
Encryption details is missing 

### ISSUE THREAD

**Issue by EimantasPelikis** [ibm-cloud-docs/databases-for-postgresql#8]
This page in IBM Cloud docs: https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-security-compliance
is missing more specific details about data encryption at rest, e.g. which encryption algorithm is used what are the encryption standard supported?

**Comment by DailyAlice** [comment]
Added some details about disk encryption, LUKS AES-256, keys are managed with Key Protect. Hopefully it helps!
