### ISSUE TITLE
ibm-cloud-base-user and ibm-cloud-base-user-ro not decribed 

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/databases-for-postgresql#9]
https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-user-management
The roles list mentioned two IBM defined roles
ibm-cloud-base-user  ibm-cloud-base-user-ro

In the description section these roles are not described. Could they please be added. Thanks

**Comment by DailyAlice** [comment]
Expanded the IBM users section to cover `ibm-cloud-base-user` - https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-user-management#other-ibm-users

The `ibm-cloud-base-user-ro` is in - https://cloud.ibm.com/docs/services/databases-for-postgresql?topic=databases-for-postgresql-user-management#the-read-only-user

Thanks!
